#!/usr/bin/env ruby
require 'haml-rails'

def system!(*args)
  system(*args) || abort("\n== Command #{args} failed ==")
end

system! 'bin/rails g haml:application_layout convert'
system! 'bin/rake haml:erb2haml'
